config/routes.rb
Rails.application.routes.draw do

  post '/api/report' => 'reports#create'
  resources :reports, only: [ :index, :show, :destroy ]

  root 'reports#index'

end

app/models/report.rb
class Report < ActiveRecord::Base

  validates :uuid, presence: true, uniqueness: true
  validates :keyserver_url, presence: true
  validates :owner_id, presence: true

  mount_uploader :encrypted_file, EncryptedReportUploader

  def owner_name
    [ owner_first_name, owner_last_name ].reject(&:blank?).join(" ")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  protect_from_forgery except: :create

  # shows all reports that we have
  def index
    @reports = Report.order("created_at DESC").all
  end

  # returns decrypted report
  def show
    respond_to do |format|
      format.zip do
        report = Report.find(params[:id])
        file   = DecryptReport.perform(report)
        send_file file, type: 'application/zip', filename: "#{report.uuid}.zip"
      end
    end
  end

  # stores the report coming from the app
  def create
    StoreReport.perform(report_params)
    render json: { success: true }
  rescue StoreReport::Error => e
    render json: { success: false, error: e.message }
  end

  # deletes the report
  def destroy
    Report.find(params[:id]).destroy
    redirect_to :reports, notice: "Report has been deleted"
  end

  private

  def report_params
    params.permit(:token, :picsafe_file)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo PicSafe Endpoint</title>
  <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-dark bg-primary">
    <a class="navbar-brand" href="/">Demo PicSafe Endpoint</a>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/">Reports</a>
      </li>
    </ul>
  </nav>
  </br>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/reports/index.html.erb
<h1>Reports</h1>

<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Owner name</th>
      <th>Owner email</th>
      <th>Owner country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @reports.empty? %>
      <tr>
        <td colspan="7">
          <p class="text-muted">There are no reports submitted yet</p>
        </td>
      </tr>
      <tr>
        <td colspan="7">
          To send a report, make the API call to:
          <p>
            <code>
              POST /api/report
            </code>
          </p>
          <p>Parameters:</p>
          <ul>
            <li><strong>picsafe_file</strong> -- file to upload. Unencrypted file should contain:
              <ul>
                <li>Report ID in the name of the file. For example: <code>0000000011462800528240.picsafe</code></li>
                <li><code>package.json</code> with key server URL in <code>keyserver_url</code> key.</li>
                <li><code>package.encrypted</code> with encrypted ZIP file.</li>
              </ul>
            </li>
            <li><strong>token</strong> -- the same user token you used to get encryption key from the key server</li>
          </ul>

          <p>Returns:</p>
          <ul>
            <li>{ success: true }</li>
            <li>{ success: false, error: "Error message" }</li>
          </ul>
        </td>
      </tr>
    <% else %>
      <% @reports.each do |r| %>
        <tr>
          <td><%= r.uuid %></td>
          <td><%= r.owner_name %></td>
          <td><%= r.owner_email %></td>
          <td><%= r.owner_country %></td>
          <td><%= link_to 'Decrypt', report_url(r, format: 'zip') %></td>
          <td><%= link_to 'Destroy', r, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>